// Code generated by yo. DO NOT EDIT.
// Package models contains the types.
package models

import (
	"context"
	"fmt"
	"math/big"

	"cloud.google.com/go/spanner"
	"google.golang.org/grpc/codes"
)

// Account represents a row from 'Accounts'.
type Account struct {
	TenantID  string  `spanner:"TenantID" json:"TenantID"`   // TenantID
	AccountID string  `spanner:"AccountID" json:"AccountID"` // AccountID
	Name      string  `spanner:"Name" json:"Name"`           // Name
	Balance   big.Rat `spanner:"Balance" json:"Balance"`     // Balance
}

func AccountPrimaryKeys() []string {
	return []string{
		"TenantID",
		"AccountID",
	}
}

func AccountColumns() []string {
	return []string{
		"TenantID",
		"AccountID",
		"Name",
		"Balance",
	}
}

func AccountWritableColumns() []string {
	return []string{
		"TenantID",
		"AccountID",
		"Name",
		"Balance",
	}
}

func (a *Account) columnsToPtrs(cols []string, customPtrs map[string]interface{}) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		if val, ok := customPtrs[col]; ok {
			ret = append(ret, val)
			continue
		}

		switch col {
		case "TenantID":
			ret = append(ret, &a.TenantID)
		case "AccountID":
			ret = append(ret, &a.AccountID)
		case "Name":
			ret = append(ret, &a.Name)
		case "Balance":
			ret = append(ret, &a.Balance)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}
	return ret, nil
}

func (a *Account) columnsToValues(cols []string) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		switch col {
		case "TenantID":
			ret = append(ret, a.TenantID)
		case "AccountID":
			ret = append(ret, a.AccountID)
		case "Name":
			ret = append(ret, a.Name)
		case "Balance":
			ret = append(ret, a.Balance)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}

	return ret, nil
}

// newAccount_Decoder returns a decoder which reads a row from *spanner.Row
// into Account. The decoder is not goroutine-safe. Don't use it concurrently.
func newAccount_Decoder(cols []string) func(*spanner.Row) (*Account, error) {
	customPtrs := map[string]interface{}{}

	return func(row *spanner.Row) (*Account, error) {
		var a Account
		ptrs, err := a.columnsToPtrs(cols, customPtrs)
		if err != nil {
			return nil, err
		}

		if err := row.Columns(ptrs...); err != nil {
			return nil, err
		}

		return &a, nil
	}
}

// Insert returns a Mutation to insert a row into a table. If the row already
// exists, the write or transaction fails.
func (a *Account) Insert(ctx context.Context) *spanner.Mutation {
	values, _ := a.columnsToValues(AccountWritableColumns())
	return spanner.Insert("Accounts", AccountWritableColumns(), values)
}

// Update returns a Mutation to update a row in a table. If the row does not
// already exist, the write or transaction fails.
func (a *Account) Update(ctx context.Context) *spanner.Mutation {
	values, _ := a.columnsToValues(AccountWritableColumns())
	return spanner.Update("Accounts", AccountWritableColumns(), values)
}

// InsertOrUpdate returns a Mutation to insert a row into a table. If the row
// already exists, it updates it instead. Any column values not explicitly
// written are preserved.
func (a *Account) InsertOrUpdate(ctx context.Context) *spanner.Mutation {
	values, _ := a.columnsToValues(AccountWritableColumns())
	return spanner.InsertOrUpdate("Accounts", AccountWritableColumns(), values)
}

// UpdateColumns returns a Mutation to update specified columns of a row in a table.
func (a *Account) UpdateColumns(ctx context.Context, cols ...string) (*spanner.Mutation, error) {
	// add primary keys to columns to update by primary keys
	colsWithPKeys := append(cols, AccountPrimaryKeys()...)

	values, err := a.columnsToValues(colsWithPKeys)
	if err != nil {
		return nil, newErrorWithCode(codes.InvalidArgument, "Account.UpdateColumns", "Accounts", err)
	}

	return spanner.Update("Accounts", colsWithPKeys, values), nil
}

// FindAccount gets a Account by primary key
func FindAccount(ctx context.Context, db YORODB, tenantID string, accountID string) (*Account, error) {
	key := spanner.Key{tenantID, accountID}
	row, err := db.ReadRow(ctx, "Accounts", key, AccountColumns())
	if err != nil {
		return nil, newError("FindAccount", "Accounts", err)
	}

	decoder := newAccount_Decoder(AccountColumns())
	a, err := decoder(row)
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "FindAccount", "Accounts", err)
	}

	return a, nil
}

// ReadAccount retrieves multiples rows from Account by KeySet as a slice.
func ReadAccount(ctx context.Context, db YORODB, keys spanner.KeySet) ([]*Account, error) {
	var res []*Account

	decoder := newAccount_Decoder(AccountColumns())

	rows := db.Read(ctx, "Accounts", keys, AccountColumns())
	err := rows.Do(func(row *spanner.Row) error {
		a, err := decoder(row)
		if err != nil {
			return err
		}
		res = append(res, a)

		return nil
	})
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "ReadAccount", "Accounts", err)
	}

	return res, nil
}

// Delete deletes the Account from the database.
func (a *Account) Delete(ctx context.Context) *spanner.Mutation {
	values, _ := a.columnsToValues(AccountPrimaryKeys())
	return spanner.Delete("Accounts", spanner.Key(values))
}
