// Code generated by yo. DO NOT EDIT.
// Package models contains the types.
package models

import (
	"context"
	"fmt"
	"math/big"
	"time"

	"cloud.google.com/go/spanner"
	"google.golang.org/api/iterator"
	"google.golang.org/grpc/codes"
)

// Transaction represents a row from 'Transactions'.
type Transaction struct {
	TenantID        string    `spanner:"TenantID" json:"TenantID"`               // TenantID
	AccountID       string    `spanner:"AccountID" json:"AccountID"`             // AccountID
	TransactionID   string    `spanner:"TransactionID" json:"TransactionID"`     // TransactionID
	Amount          big.Rat   `spanner:"Amount" json:"Amount"`                   // Amount
	CreatedAt       time.Time `spanner:"CreatedAt" json:"CreatedAt"`             // CreatedAt
	TransactionType string    `spanner:"TransactionType" json:"TransactionType"` // TransactionType
	ReferenceID     string    `spanner:"ReferenceID" json:"ReferenceID"`         // ReferenceID
}

func TransactionPrimaryKeys() []string {
	return []string{
		"TenantID",
		"AccountID",
		"TransactionID",
	}
}

func TransactionColumns() []string {
	return []string{
		"TenantID",
		"AccountID",
		"TransactionID",
		"Amount",
		"CreatedAt",
		"TransactionType",
		"ReferenceID",
	}
}

func TransactionWritableColumns() []string {
	return []string{
		"TenantID",
		"AccountID",
		"TransactionID",
		"Amount",
		"CreatedAt",
		"TransactionType",
		"ReferenceID",
	}
}

func (t *Transaction) columnsToPtrs(cols []string, customPtrs map[string]interface{}) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		if val, ok := customPtrs[col]; ok {
			ret = append(ret, val)
			continue
		}

		switch col {
		case "TenantID":
			ret = append(ret, &t.TenantID)
		case "AccountID":
			ret = append(ret, &t.AccountID)
		case "TransactionID":
			ret = append(ret, &t.TransactionID)
		case "Amount":
			ret = append(ret, &t.Amount)
		case "CreatedAt":
			ret = append(ret, &t.CreatedAt)
		case "TransactionType":
			ret = append(ret, &t.TransactionType)
		case "ReferenceID":
			ret = append(ret, &t.ReferenceID)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}
	return ret, nil
}

func (t *Transaction) columnsToValues(cols []string) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		switch col {
		case "TenantID":
			ret = append(ret, t.TenantID)
		case "AccountID":
			ret = append(ret, t.AccountID)
		case "TransactionID":
			ret = append(ret, t.TransactionID)
		case "Amount":
			ret = append(ret, t.Amount)
		case "CreatedAt":
			ret = append(ret, t.CreatedAt)
		case "TransactionType":
			ret = append(ret, t.TransactionType)
		case "ReferenceID":
			ret = append(ret, t.ReferenceID)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}

	return ret, nil
}

// newTransaction_Decoder returns a decoder which reads a row from *spanner.Row
// into Transaction. The decoder is not goroutine-safe. Don't use it concurrently.
func newTransaction_Decoder(cols []string) func(*spanner.Row) (*Transaction, error) {
	customPtrs := map[string]interface{}{}

	return func(row *spanner.Row) (*Transaction, error) {
		var t Transaction
		ptrs, err := t.columnsToPtrs(cols, customPtrs)
		if err != nil {
			return nil, err
		}

		if err := row.Columns(ptrs...); err != nil {
			return nil, err
		}

		return &t, nil
	}
}

// Insert returns a Mutation to insert a row into a table. If the row already
// exists, the write or transaction fails.
func (t *Transaction) Insert(ctx context.Context) *spanner.Mutation {
	values, _ := t.columnsToValues(TransactionWritableColumns())
	return spanner.Insert("Transactions", TransactionWritableColumns(), values)
}

// Update returns a Mutation to update a row in a table. If the row does not
// already exist, the write or transaction fails.
func (t *Transaction) Update(ctx context.Context) *spanner.Mutation {
	values, _ := t.columnsToValues(TransactionWritableColumns())
	return spanner.Update("Transactions", TransactionWritableColumns(), values)
}

// InsertOrUpdate returns a Mutation to insert a row into a table. If the row
// already exists, it updates it instead. Any column values not explicitly
// written are preserved.
func (t *Transaction) InsertOrUpdate(ctx context.Context) *spanner.Mutation {
	values, _ := t.columnsToValues(TransactionWritableColumns())
	return spanner.InsertOrUpdate("Transactions", TransactionWritableColumns(), values)
}

// UpdateColumns returns a Mutation to update specified columns of a row in a table.
func (t *Transaction) UpdateColumns(ctx context.Context, cols ...string) (*spanner.Mutation, error) {
	// add primary keys to columns to update by primary keys
	colsWithPKeys := append(cols, TransactionPrimaryKeys()...)

	values, err := t.columnsToValues(colsWithPKeys)
	if err != nil {
		return nil, newErrorWithCode(codes.InvalidArgument, "Transaction.UpdateColumns", "Transactions", err)
	}

	return spanner.Update("Transactions", colsWithPKeys, values), nil
}

// FindTransaction gets a Transaction by primary key
func FindTransaction(ctx context.Context, db YORODB, tenantID string, accountID string, transactionID string) (*Transaction, error) {
	key := spanner.Key{tenantID, accountID, transactionID}
	row, err := db.ReadRow(ctx, "Transactions", key, TransactionColumns())
	if err != nil {
		return nil, newError("FindTransaction", "Transactions", err)
	}

	decoder := newTransaction_Decoder(TransactionColumns())
	t, err := decoder(row)
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "FindTransaction", "Transactions", err)
	}

	return t, nil
}

// ReadTransaction retrieves multiples rows from Transaction by KeySet as a slice.
func ReadTransaction(ctx context.Context, db YORODB, keys spanner.KeySet) ([]*Transaction, error) {
	var res []*Transaction

	decoder := newTransaction_Decoder(TransactionColumns())

	rows := db.Read(ctx, "Transactions", keys, TransactionColumns())
	err := rows.Do(func(row *spanner.Row) error {
		t, err := decoder(row)
		if err != nil {
			return err
		}
		res = append(res, t)

		return nil
	})
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "ReadTransaction", "Transactions", err)
	}

	return res, nil
}

// Delete deletes the Transaction from the database.
func (t *Transaction) Delete(ctx context.Context) *spanner.Mutation {
	values, _ := t.columnsToValues(TransactionPrimaryKeys())
	return spanner.Delete("Transactions", spanner.Key(values))
}

// FindTransactionsByAmountTransactionTypeReferenceID retrieves multiple rows from 'Transactions' as a slice of Transaction.
//
// Generated from index 'TransactionsByReferenceID'.
func FindTransactionsByAmountTransactionTypeReferenceID(ctx context.Context, db YORODB, referenceID string) ([]*Transaction, error) {
	const sqlstr = "SELECT " +
		"TenantID, AccountID, TransactionID, Amount, CreatedAt, TransactionType, ReferenceID " +
		"FROM Transactions@{FORCE_INDEX=TransactionsByReferenceID} " +
		"WHERE ReferenceID = @param0"

	stmt := spanner.NewStatement(sqlstr)
	stmt.Params["param0"] = referenceID

	decoder := newTransaction_Decoder(TransactionColumns())

	// run query
	YOLog(ctx, sqlstr, referenceID)
	iter := db.Query(ctx, stmt)
	defer iter.Stop()

	// load results
	res := []*Transaction{}
	for {
		row, err := iter.Next()
		if err != nil {
			if err == iterator.Done {
				break
			}
			return nil, newError("FindTransactionsByAmountTransactionTypeReferenceID", "Transactions", err)
		}

		t, err := decoder(row)
		if err != nil {
			return nil, newErrorWithCode(codes.Internal, "FindTransactionsByAmountTransactionTypeReferenceID", "Transactions", err)
		}

		res = append(res, t)
	}

	return res, nil
}

// ReadTransactionsByAmountTransactionTypeReferenceID retrieves multiples rows from 'Transactions' by KeySet as a slice.
//
// This does not retrieve all columns of 'Transactions' because an index has only columns
// used for primary key, index key and storing columns. If you need more columns, add storing
// columns or Read by primary key or Query with join.
//
// Generated from unique index 'TransactionsByReferenceID'.
func ReadTransactionsByAmountTransactionTypeReferenceID(ctx context.Context, db YORODB, keys spanner.KeySet) ([]*Transaction, error) {
	var res []*Transaction
	columns := []string{
		"TenantID",
		"AccountID",
		"TransactionID",
		"ReferenceID",
		"Amount",
		"TransactionType",
	}

	decoder := newTransaction_Decoder(columns)

	rows := db.ReadUsingIndex(ctx, "Transactions", "TransactionsByReferenceID", keys, columns)
	err := rows.Do(func(row *spanner.Row) error {
		t, err := decoder(row)
		if err != nil {
			return err
		}
		res = append(res, t)

		return nil
	})
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "ReadTransactionsByAmountTransactionTypeReferenceID", "Transactions", err)
	}

	return res, nil
}
